### ISSUE TITLE
Question-Nameless Window

### ISSUE THREAD

**Issue by PaperHammer** [reactivemarbles/CrissCross#133]
When using WebView2Wpf in CrissCross, holding down Alt + Tab will bring up a nameless window. It won't show up in the taskbar and task manager, is this normal? What is the purpose of this window?

当使用 CrissCross 中的 WebView2Wpf 时，按住 Alt + Tab 会出现一个无名的窗口。它不会显示到任务栏和任务管理器中，请问这是否正常？这个窗口的作用是什么？

<img width="596" alt="1" src="https://github.com/reactivemarbles/CrissCross/assets/98168954/eb8226a0-73a7-4fa5-a9f6-f26d7e277168">

**Comment by ChrisPulman** [comment]
This is the Wpf host window for the browser overlay, I will look into hiding it from Alt Tab too as I hid it from the taskbar and task manager.
Thank you for pointing this out.

**Comment by PaperHammer** [comment]
Thank you for the explanation, and I will continue to stay tuned and look forward to future versions!

感谢您的解释，我也会继续关注，期待之后版本！
